name: Deployment

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: mustachebash-admin
          token: ${{ secrets.DIGITALOCEAN_PAT }}
          images: '[
              {
                "name": "static-server",
                "image":{
                  "registry_type": "GHCR",
                  "registry": "mustachebash",
                  "repository": "admin",
                  "digest": "sha256:1c5292d582b0d3d524b6ceebbcd6ac6d5b11688ef205ac1dc518e5352f75305e"
                }
            ]'
